version: "3.3"
services:
  risk-tool:
    build: ./risk-tool
    image: alexwese/risk-tool:latest
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    #networks:
    #  - gateway

  prophetservice:
    build: Forecast/API/.
    image: alexwese/prophetservice:latest
    ports:
    - '8061:8061'
    expose:
      - '8061'

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
      #- '127.0.0.1:3306:3306'
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted

    #command: --init-file allsql.sql
    volumes:
      - my-db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  backend:
    build: Backend-New/.
    image: alexwese/risk-tool-backend:latest
    ports:
      - '8080:8080'
    #networks:
    #  - gateway
    #links:
    #  - "risk-db:database"
    links:
    - db
    depends_on:
        - db

# Names our volume
volumes:
  my-db:
